name: ruta_facil
description: "Aplicación de ruteo y optimización logística para repartidores."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # UI e Íconos
  cupertino_icons: ^1.0.8

  # Mapas y Geolocalización
  google_maps_flutter: ^2.9.0
  geolocator: ^14.0.3

  # Networking y APIs
  http: ^1.6.0
  url_launcher: ^6.3.2

  # Base de Datos Local
  sqflite: ^2.4.3
  path: ^1.9.1

  # Configuración y Enlaces de WhatsApp
  flutter_dotenv: ^6.0.1
  app_links: ^6.3.2
  file_picker: ^12.0.0

  # Notificación Interactiva de Despacho
  flutter_local_notifications: ^18.0.1

  # Escáner OCR de Etiquetas
  google_mlkit_text_recognition: ^0.14.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env